### ISSUE TITLE
Compression detection with deep learning

### ISSUE THREAD

**Issue by valosekj** [neuropoly/idea-projects#4] opened 2022-12-21 17:52 UTC
Within a parallel project focused on [morphometric metrics normalization](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3733), we will obtain ground-true information about the level of compression across many DCM patients. The level of compression for each patient will be stored within a [NIfTI file as a single voxel value](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3984). The NIfTI file will have the same dimension as the source image.
A deep learning model could then be trained to detect the compression automatically.  

See relevant [previous study](https://www.nature.com/articles/s41598-021-89848-3); also explained as a [blog post](https://medium.com/@zamir.merali/a-deep-learning-model-to-detect-spinal-cord-compression-in-cervical-spine-mri-scans-f2e366663235).

**Comment by naga-karthik** [comment] 2023-01-19 16:56
Regression problem - model predicts a list of slice numbers which have some compression (or not) for each subject. 
Need to try both 2D and 3D models 
Do we need the model to predict a single slice that's maximally compressed or multiple slices at each disk that show the compression? How do we define the labels (for training the model) in this case?

Inputs to the model?
* The T2w sagittal image (as a first step), to be upgraded to different image orientation and different contrasts
* Disk labels (e.g. C4, C5, etc) which is a single voxel value  stored as a .nii.gz files. This is similar to what's seen [here](https://spinalcordtoolbox.com/user_section/tutorials/registration-to-template/vertebral-labeling/labeling-conventions.html). 
* Compression labels (also single voxel values) as described [here](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3984#issuecomment-1373008539).

**Comment by jcohenadad** [comment] 2023-01-19 17:42
Good thoughts @naga-karthik . I was originally thinking of inputting the morphometrics values (CSA, torsion, AP diameter, etc.) derived from the segmentation and train a simple regression model (no deep learning), but that might be a reduction of the richness of information provided by the actual MRI image, where a CNN could potentially perform better. We need to try both!

I don't think inputing the disc labels will be necessary. However, if we go the CNN route, inputting the T2w image, the cord segmentation (to "help" the CNN) and the compression labels will be necessary.

**Comment by valosekj** [comment] 2023-01-19 17:55
> I don't think inputing the disc labels will be necessary.

We thought that disc labels might be useful since SC anatomy varies along the S-I direction. So, the disc labels might "help" the CNN.

> However, if we go the CNN route, inputting the T2w image, the cord segmentation (to "help" the CNN) and the compression labels will be necessary.

Is cord segmentation really necessary? During our discussion with Naga, we thought that from the practical point of view, it would be better not to use the segmentation (because segmentation in compressed SC often requires time-consuming manual corrections). But still, we can use automatically obtained segmentation or centerline for input image cropping before running CNN.

**Comment by naga-karthik** [comment] 2023-01-19 18:23
@jcohenadad Thanks for your suggestions! However, I don't see how the cord segmentation would be useful, unless we colour code the segmentation mask differently for regions where the spinal cord is compressed. Then, we can turn it into a 3-class segmentation problem (class 0: background, class 1: normal SC seg mask, class 2: compressed SC regions). I also think that it is unnecessary to make it a segmentation problem again.

**Comment by jcohenadad** [comment] 2023-01-19 18:48
> We thought that disc labels might be useful since SC anatomy varies along the S-I direction. So, the disc labels might "help" the CNN.

right, but I'm not sure how to encode this information into a CNN (as another channel? i'm not sure the conv filters will properly encode the information).

> Is cord segmentation really necessary? During our discussion with Naga, we thought that from the practical point of view, it would be better not to use the segmentation (because segmentation in compressed SC often requires time-consuming manual corrections). But still, we can use automatically obtained segmentation or centerline for input image cropping before running CNN.

This is what I meant: cord segmentation _only_ to select a subset of patches to go into the CNN (as proposed in https://github.com/ivadomed/ivadomed/issues/1259#issuecomment-1371528151). This also addresses https://github.com/neuropoly/idea-projects/issues/4#issuecomment-1397422439.

**Comment by jcohenadad** [comment] 2023-08-01 15:24
duplicate of https://github.com/neuropoly/idea-projects/issues/2

**Closed by jcohenadad** 2023-08-01 15:24 UTC
Labels: ivadomed
